-- ============================================================
-- BMedia — Admin User Seed Script
--
-- STEP 1: Generate the password hash FIRST by running:
--         dotnet run --project tools/GenerateHash
--         (enter password "Admin@123" or your own password)
--
-- STEP 2: Replace <PASTE_BCRYPT_HASH_HERE> below with the
--         generated hash, then run this script in psql.
--
-- STEP 3: Run in psql:
--         \i SeedAdmin.sql
--
-- What this script does:
--   1. Creates an admin user (admin@bmedia.io / Admin@123)
--   2. Assigns the Administrator role to that user
--   3. Assigns ALL 17 permissions to the Administrator role
-- ============================================================

BEGIN;

DO $$
DECLARE
    v_user_id    uuid        := gen_random_uuid();
    v_admin_role uuid        := '10000000-0000-0000-0000-000000000001';
    v_now        timestamptz := NOW();
    v_hash       text        := '<PASTE_BCRYPT_HASH_HERE>';
BEGIN

    -- --------------------------------------------------------
    -- Guard: abort if hash placeholder was not replaced
    -- --------------------------------------------------------
    IF v_hash = '<PASTE_BCRYPT_HASH_HERE>' THEN
        RAISE EXCEPTION
            'Replace <PASTE_BCRYPT_HASH_HERE> with the BCrypt hash '
            'generated by: dotnet run --project tools/GenerateHash';
    END IF;

    -- --------------------------------------------------------
    -- Guard: skip if admin user already exists
    -- --------------------------------------------------------
    IF EXISTS (SELECT 1 FROM users WHERE username = 'admin' AND is_deleted = false) THEN
        RAISE NOTICE 'Admin user already exists — skipping user insert.';
    ELSE
        INSERT INTO users (
            id,
            username,
            email,
            password_hash,
            first_name,
            last_name,
            is_active,
            is_email_verified,
            failed_login_attempts,
            preferred_language,
            created_at,
            is_deleted
        ) VALUES (
            v_user_id,
            'admin',
            'admin@bmedia.io',
            v_hash,
            'System',
            'Admin',
            true,
            true,       -- email already verified so login works immediately
            0,
            'en',
            v_now,
            false
        );

        RAISE NOTICE 'Admin user created — ID: %', v_user_id;
    END IF;

    -- --------------------------------------------------------
    -- Read the user id back (in case user already existed)
    -- --------------------------------------------------------
    SELECT id INTO v_user_id
    FROM users
    WHERE username = 'admin' AND is_deleted = false;

    -- --------------------------------------------------------
    -- Assign Administrator role to user
    -- --------------------------------------------------------
    INSERT INTO user_roles (user_id, role_id, assigned_at)
    VALUES (v_user_id, v_admin_role, v_now)
    ON CONFLICT (user_id, role_id) DO NOTHING;

    RAISE NOTICE 'Administrator role assigned to user %.', v_user_id;

    -- --------------------------------------------------------
    -- Assign ALL 17 permissions to Administrator role
    -- --------------------------------------------------------
    INSERT INTO role_permissions (role_id, permission_id, granted_at)
    SELECT v_admin_role, id, v_now
    FROM   permissions
    WHERE  is_deleted = false
    ON CONFLICT (role_id, permission_id) DO NOTHING;

    RAISE NOTICE 'All permissions granted to Administrator role.';

END $$;

COMMIT;

-- ============================================================
-- Verify — show what was inserted
-- ============================================================
SELECT
    u.id,
    u.username,
    u.email,
    u.is_active,
    u.is_email_verified,
    r.name  AS role,
    COUNT(rp.permission_id) AS permission_count
FROM users u
JOIN user_roles      ur ON ur.user_id      = u.id
JOIN roles           r  ON r.id            = ur.role_id
JOIN role_permissions rp ON rp.role_id     = r.id
WHERE u.username   = 'admin'
  AND u.is_deleted = false
GROUP BY u.id, u.username, u.email, u.is_active, u.is_email_verified, r.name;
