// <auto-generated />
using System;
using BMedia.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BMedia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BMedia.Domain.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id").HasDefaultValueSql("gen_random_uuid()").HasColumnName("id");
                b.Property<int>("Action").HasColumnName("action");
                b.Property<string>("AdditionalData").HasColumnType("jsonb").HasColumnName("additional_data");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at");
                b.Property<Guid?>("CreatedBy").HasColumnName("created_by");
                b.Property<DateTime?>("DeletedAt").HasColumnName("deleted_at");
                b.Property<Guid?>("DeletedBy").HasColumnName("deleted_by");
                b.Property<string>("EntityId").HasMaxLength(100).HasColumnName("entity_id");
                b.Property<string>("EntityType").IsRequired().HasMaxLength(200).HasColumnName("entity_type");
                b.Property<string>("ErrorMessage").HasMaxLength(2000).HasColumnName("error_message");
                b.Property<string>("IpAddress").HasMaxLength(50).HasColumnName("ip_address");
                b.Property<bool>("IsDeleted").HasColumnName("is_deleted");
                b.Property<bool>("IsSuccessful").HasColumnName("is_successful");
                b.Property<string>("NewValues").HasColumnType("jsonb").HasColumnName("new_values");
                b.Property<string>("OldValues").HasColumnType("jsonb").HasColumnName("old_values");
                b.Property<uint>("RowVersion").IsRowVersion().IsConcurrencyToken().HasColumnName("row_version");
                b.Property<DateTime?>("UpdatedAt").HasColumnName("updated_at");
                b.Property<Guid?>("UpdatedBy").HasColumnName("updated_by");
                b.Property<string>("UserAgent").HasMaxLength(512).HasColumnName("user_agent");
                b.Property<string>("UserEmail").HasMaxLength(256).HasColumnName("user_email");
                b.Property<Guid?>("UserId").HasColumnName("user_id");
                b.HasKey("Id").HasName("pk_audit_logs");
                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("BMedia.Domain.Entities.Category", b =>
            {
                b.Property<Guid>("Id").HasDefaultValueSql("gen_random_uuid()").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at");
                b.Property<Guid?>("CreatedBy").HasColumnName("created_by");
                b.Property<DateTime?>("DeletedAt").HasColumnName("deleted_at");
                b.Property<Guid?>("DeletedBy").HasColumnName("deleted_by");
                b.Property<string>("Description").HasMaxLength(1000).HasColumnName("description");
                b.Property<string>("IconUrl").HasMaxLength(2048).HasColumnName("icon_url");
                b.Property<bool>("IsActive").HasColumnName("is_active");
                b.Property<bool>("IsDeleted").HasColumnName("is_deleted");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnName("name");
                b.Property<uint>("RowVersion").IsRowVersion().IsConcurrencyToken().HasColumnName("row_version");
                b.Property<string>("Slug").IsRequired().HasMaxLength(250).HasColumnName("slug");
                b.Property<int>("SortOrder").HasColumnName("sort_order");
                b.Property<DateTime?>("UpdatedAt").HasColumnName("updated_at");
                b.Property<Guid?>("UpdatedBy").HasColumnName("updated_by");
                b.HasKey("Id").HasName("pk_categories");
                b.HasIndex("Slug").IsUnique().HasDatabaseName("ix_categories_slug").HasFilter("\"IsDeleted\" = false");
                b.ToTable("Categories");
            });

            modelBuilder.Entity("BMedia.Domain.Entities.Content", b =>
            {
                b.Property<Guid>("Id").HasDefaultValueSql("gen_random_uuid()").HasColumnName("id");
                b.Property<bool>("AllowComments").HasColumnName("allow_comments");
                b.Property<DateTime?>("ArchivedAt").HasColumnName("archived_at");
                b.Property<Guid?>("AssignedReviewerId").HasColumnName("assigned_reviewer_id");
                b.Property<string>("Body").HasColumnType("text").HasColumnName("body");
                b.Property<string>("CanonicalUrl").HasMaxLength(2048).HasColumnName("canonical_url");
                b.Property<Guid?>("CategoryId").HasColumnName("category_id");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at");
                b.Property<Guid?>("CreatedBy").HasColumnName("created_by");
                b.Property<Guid?>("CurrentWorkflowStepId").HasColumnName("current_workflow_step_id");
                b.Property<DateTime?>("DeletedAt").HasColumnName("deleted_at");
                b.Property<Guid?>("DeletedBy").HasColumnName("deleted_by");
                b.Property<bool>("IsFeatured").HasColumnName("is_featured");
                b.Property<bool>("IsDeleted").HasColumnName("is_deleted");
                b.Property<string>("Language").IsRequired().HasMaxLength(10).HasDefaultValue("en").HasColumnName("language");
                b.Property<DateTime?>("PublishedAt").HasColumnName("published_at");
                b.Property<Guid?>("PublishedBy").HasColumnName("published_by");
                b.Property<uint>("RowVersion").IsRowVersion().IsConcurrencyToken().HasColumnName("row_version");
                b.Property<DateTime?>("ScheduledPublishAt").HasColumnName("scheduled_publish_at");
                b.Property<string>("SeoDescription").HasMaxLength(500).HasColumnName("seo_description");
                b.Property<string>("SeoKeywords").HasMaxLength(500).HasColumnName("seo_keywords");
                b.Property<string>("SeoTitle").HasMaxLength(300).HasColumnName("seo_title");
                b.Property<string>("Slug").IsRequired().HasMaxLength(600).HasColumnName("slug");
                b.Property<int>("Status").HasDefaultValue(1).HasColumnName("status");
                b.Property<Guid?>("SubcategoryId").HasColumnName("subcategory_id");
                b.Property<string>("Summary").HasMaxLength(2000).HasColumnName("summary");
                b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnName("title");
                b.Property<DateTime?>("UpdatedAt").HasColumnName("updated_at");
                b.Property<Guid?>("UpdatedBy").HasColumnName("updated_by");
                b.Property<int>("ViewCount").HasColumnName("view_count");
                b.HasKey("Id").HasName("pk_contents");
                b.HasIndex("Slug").IsUnique().HasDatabaseName("ix_contents_slug").HasFilter("\"IsDeleted\" = false");
                b.HasIndex("Status").HasDatabaseName("ix_contents_status");
                b.HasIndex("CategoryId").HasDatabaseName("ix_contents_category_id");
                b.HasIndex("PublishedAt").HasDatabaseName("ix_contents_published_at");
                b.ToTable("Contents");
            });

            modelBuilder.Entity("BMedia.Domain.Entities.MediaAsset", b =>
            {
                b.Property<Guid>("Id").HasDefaultValueSql("gen_random_uuid()").HasColumnName("id");
                b.Property<string>("AiGeneratedTags").HasColumnType("jsonb").HasColumnName("ai_generated_tags");
                b.Property<string>("AltText").HasMaxLength(500).HasColumnName("alt_text");
                b.Property<bool>("AntivirusScanPassed").HasColumnName("antivirus_scan_passed");
                b.Property<DateTime?>("AntivirusScannedAt").HasColumnName("antivirus_scanned_at");
                b.Property<double?>("AspectRatio").HasColumnName("aspect_ratio");
                b.Property<int?>("Bitrate").HasColumnName("bitrate");
                b.Property<string>("CdnUrl").HasMaxLength(2048).HasColumnName("cdn_url");
                b.Property<string>("Codec").HasMaxLength(100).HasColumnName("codec");
                b.Property<Guid?>("ContentId").HasColumnName("content_id");
                b.Property<string>("ContentType").IsRequired().HasMaxLength(255).HasColumnName("content_type");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at");
                b.Property<Guid?>("CreatedBy").HasColumnName("created_by");
                b.Property<DateTime?>("DeletedAt").HasColumnName("deleted_at");
                b.Property<Guid?>("DeletedBy").HasColumnName("deleted_by");
                b.Property<string>("Description").HasMaxLength(2000).HasColumnName("description");
                b.Property<int?>("DurationSeconds").HasColumnName("duration_seconds");
                b.Property<string>("ExtractedMetadata").HasColumnType("jsonb").HasColumnName("extracted_metadata");
                b.Property<long>("FileSizeBytes").HasColumnName("file_size_bytes");
                b.Property<double?>("FrameRate").HasColumnName("frame_rate");
                b.Property<int?>("Height").HasColumnName("height");
                b.Property<string>("HlsManifestUrl").HasMaxLength(2048).HasColumnName("hls_manifest_url");
                b.Property<bool>("IsDeleted").HasColumnName("is_deleted");
                b.Property<bool>("IsMetadataExtracted").HasColumnName("is_metadata_extracted");
                b.Property<bool>("IsPrimary").HasColumnName("is_primary");
                b.Property<bool>("IsThumbnailGenerated").HasColumnName("is_thumbnail_generated");
                b.Property<bool>("IsTranscodingComplete").HasColumnName("is_transcoding_complete");
                b.Property<bool>("IsWatermarked").HasColumnName("is_watermarked");
                b.Property<string>("Language").IsRequired().HasMaxLength(10).HasDefaultValue("en").HasColumnName("language");
                b.Property<int>("MediaType").HasColumnName("media_type");
                b.Property<string>("OcrText").HasColumnType("text").HasColumnName("ocr_text");
                b.Property<string>("OriginalFileName").IsRequired().HasMaxLength(512).HasColumnName("original_file_name");
                b.Property<string>("PreviewUrl").HasMaxLength(2048).HasColumnName("preview_url");
                b.Property<string>("PublicUrl").HasMaxLength(2048).HasColumnName("public_url");
                b.Property<uint>("RowVersion").IsRowVersion().IsConcurrencyToken().HasColumnName("row_version");
                b.Property<int>("SortOrder").HasColumnName("sort_order");
                b.Property<int>("Status").HasDefaultValue(1).HasColumnName("status");
                b.Property<int>("StorageProvider").HasDefaultValue(1).HasColumnName("storage_provider");
                b.Property<string>("StorageKey").IsRequired().HasMaxLength(1024).HasColumnName("storage_key");
                b.Property<string>("ThumbnailUrl").HasMaxLength(2048).HasColumnName("thumbnail_url");
                b.Property<string>("Title").HasMaxLength(500).HasColumnName("title");
                b.Property<DateTime?>("UpdatedAt").HasColumnName("updated_at");
                b.Property<Guid?>("UpdatedBy").HasColumnName("updated_by");
                b.Property<int?>("Width").HasColumnName("width");
                b.HasKey("Id").HasName("pk_media_assets");
                b.HasIndex("StorageKey").IsUnique().HasDatabaseName("ix_media_assets_storage_key").HasFilter("\"IsDeleted\" = false");
                b.HasIndex("ContentId").HasDatabaseName("ix_media_assets_content_id");
                b.HasIndex("MediaType").HasDatabaseName("ix_media_assets_media_type");
                b.HasIndex("Status").HasDatabaseName("ix_media_assets_status");
                b.ToTable("MediaAssets");
            });

            modelBuilder.Entity("BMedia.Domain.Entities.Role", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at");
                b.Property<Guid?>("CreatedBy").HasColumnName("created_by");
                b.Property<DateTime?>("DeletedAt").HasColumnName("deleted_at");
                b.Property<Guid?>("DeletedBy").HasColumnName("deleted_by");
                b.Property<string>("Description").HasMaxLength(500).HasColumnName("description");
                b.Property<bool>("IsDeleted").HasColumnName("is_deleted");
                b.Property<bool>("IsSystem").HasColumnName("is_system");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnName("name");
                b.Property<string>("NormalizedName").IsRequired().HasMaxLength(100).HasColumnName("normalized_name");
                b.Property<uint>("RowVersion").IsRowVersion().IsConcurrencyToken().HasColumnName("row_version");
                b.Property<DateTime?>("UpdatedAt").HasColumnName("updated_at");
                b.Property<Guid?>("UpdatedBy").HasColumnName("updated_by");
                b.HasKey("Id").HasName("pk_roles");
                b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("ix_roles_normalized_name").HasFilter("\"IsDeleted\" = false");
                b.ToTable("Roles");
                b.HasData(
                    new { Id = new Guid("10000000-0000-0000-0000-000000000001"), Name = "Administrator", NormalizedName = "ADMINISTRATOR", IsSystem = true, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), IsDeleted = false },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000002"), Name = "ContentCreator", NormalizedName = "CONTENTCREATOR", IsSystem = true, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), IsDeleted = false },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000003"), Name = "Reviewer", NormalizedName = "REVIEWER", IsSystem = true, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), IsDeleted = false },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000004"), Name = "LanguageReviewer", NormalizedName = "LANGUAGEREVIEWER", IsSystem = true, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), IsDeleted = false },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000005"), Name = "Designer", NormalizedName = "DESIGNER", IsSystem = true, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), IsDeleted = false },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000006"), Name = "Publisher", NormalizedName = "PUBLISHER", IsSystem = true, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), IsDeleted = false },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000007"), Name = "Archivist", NormalizedName = "ARCHIVIST", IsSystem = true, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), IsDeleted = false }
                );
            });

            modelBuilder.Entity("BMedia.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").HasDefaultValueSql("gen_random_uuid()").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at");
                b.Property<Guid?>("CreatedBy").HasColumnName("created_by");
                b.Property<DateTime?>("DeletedAt").HasColumnName("deleted_at");
                b.Property<Guid?>("DeletedBy").HasColumnName("deleted_by");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnName("email");
                b.Property<string>("EmailVerificationToken").HasColumnName("email_verification_token");
                b.Property<DateTime?>("EmailVerificationTokenExpiry").HasColumnName("email_verification_token_expiry");
                b.Property<int>("FailedLoginAttempts").HasColumnName("failed_login_attempts");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnName("first_name");
                b.Property<bool>("IsActive").HasColumnName("is_active");
                b.Property<bool>("IsDeleted").HasColumnName("is_deleted");
                b.Property<bool>("IsEmailVerified").HasColumnName("is_email_verified");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnName("last_name");
                b.Property<DateTime?>("LastLoginAt").HasColumnName("last_login_at");
                b.Property<string>("LastLoginIp").HasColumnName("last_login_ip");
                b.Property<DateTime?>("LockoutEnd").HasColumnName("lockout_end");
                b.Property<string>("PasswordHash").IsRequired().HasColumnName("password_hash");
                b.Property<string>("PasswordResetToken").HasColumnName("password_reset_token");
                b.Property<DateTime?>("PasswordResetTokenExpiry").HasColumnName("password_reset_token_expiry");
                b.Property<string>("PhoneNumber").HasMaxLength(30).HasColumnName("phone_number");
                b.Property<string>("PreferredLanguage").IsRequired().HasMaxLength(10).HasDefaultValue("en").HasColumnName("preferred_language");
                b.Property<string>("ProfilePictureUrl").HasMaxLength(2048).HasColumnName("profile_picture_url");
                b.Property<uint>("RowVersion").IsRowVersion().IsConcurrencyToken().HasColumnName("row_version");
                b.Property<string>("TimeZone").HasMaxLength(100).HasColumnName("time_zone");
                b.Property<DateTime?>("UpdatedAt").HasColumnName("updated_at");
                b.Property<Guid?>("UpdatedBy").HasColumnName("updated_by");
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnName("username");
                b.HasKey("Id").HasName("pk_users");
                b.HasIndex("Email").IsUnique().HasDatabaseName("ix_users_email").HasFilter("\"IsDeleted\" = false");
                b.HasIndex("Username").IsUnique().HasDatabaseName("ix_users_username").HasFilter("\"IsDeleted\" = false");
                b.ToTable("Users");
            });

            modelBuilder.Entity("BMedia.Domain.Entities.Content", b =>
            {
                b.HasOne("BMedia.Domain.Entities.Category", "Category")
                    .WithMany("Contents")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.SetNull)
                    .HasConstraintName("fk_contents_categories_category_id");
            });

            modelBuilder.Entity("BMedia.Domain.Entities.MediaAsset", b =>
            {
                b.HasOne("BMedia.Domain.Entities.Content", "Content")
                    .WithMany("MediaAssets")
                    .HasForeignKey("ContentId")
                    .OnDelete(DeleteBehavior.SetNull)
                    .HasConstraintName("fk_media_assets_contents_content_id");
            });
#pragma warning restore 612, 618
        }
    }
}
